import { isValidElement, type ReactNode } from 'react';
import ReactMarkdown, { type Components } from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { slugify } from '@/data/kb-structure';

/**
 * Renders an article's markdown body with Dolphin typography. Server
 * component — react-markdown emits plain HTML, no client JS.
 *
 * Heading ids are derived with the shared `slugify`, so they match the
 * anchors generated by the ContentsSidebar exactly. A trailing
 * "## References" section (if present) is split off and rendered in
 * smaller type, while keeping its heading id so the contents link
 * still resolves.
 */
export function MDXContent({ content }: { content: string }) {
  const { body, references } = splitReferences(content);

  return (
    <div style={{ maxWidth: 760 }}>
      <ReactMarkdown remarkPlugins={[remarkGfm]} components={COMPONENTS}>
        {body}
      </ReactMarkdown>

      {references && (
        <div
          style={{
            marginTop: 40,
            paddingTop: 20,
            borderTop: '1px solid var(--bdr)',
            fontSize: 12.5,
            color: 'var(--muted)',
          }}
        >
          <ReactMarkdown remarkPlugins={[remarkGfm]} components={REFERENCE_COMPONENTS}>
            {references}
          </ReactMarkdown>
        </div>
      )}
    </div>
  );
}

/** Flatten react-markdown heading children into a plain string for slugging. */
function nodeToText(node: ReactNode): string {
  if (node == null || node === false) return '';
  if (typeof node === 'string' || typeof node === 'number') return String(node);
  if (Array.isArray(node)) return node.map(nodeToText).join('');
  if (isValidElement(node)) {
    return nodeToText((node.props as { children?: ReactNode }).children);
  }
  return '';
}

/** Split a trailing References section off the body. */
function splitReferences(markdown: string): { body: string; references: string | null } {
  const lines = markdown.split('\n');
  const idx = lines.findIndex((l) => /^##\s+references\s*$/i.test(l.trim()));
  if (idx === -1) return { body: markdown, references: null };
  return {
    body: lines.slice(0, idx).join('\n').trimEnd(),
    references: lines.slice(idx).join('\n').trim(),
  };
}

const COMPONENTS: Components = {
  h1: ({ children }) => (
    <h2
      id={slugify(nodeToText(children))}
      style={{ fontSize: 24, fontWeight: 600, lineHeight: 1.25, margin: '32px 0 12px', color: 'var(--text)', scrollMarginTop: 80 }}
    >
      {children}
    </h2>
  ),
  h2: ({ children }) => (
    <h2
      id={slugify(nodeToText(children))}
      style={{ fontSize: 22, fontWeight: 600, lineHeight: 1.3, margin: '34px 0 12px', color: 'var(--text)', scrollMarginTop: 80 }}
    >
      {children}
    </h2>
  ),
  h3: ({ children }) => (
    <h3
      id={slugify(nodeToText(children))}
      style={{ fontSize: 17, fontWeight: 600, lineHeight: 1.35, margin: '26px 0 10px', color: 'var(--text)', scrollMarginTop: 80 }}
    >
      {children}
    </h3>
  ),
  p: ({ children }) => (
    <p style={{ fontSize: 15.5, lineHeight: 1.75, color: 'var(--text)', margin: '0 0 18px' }}>
      {children}
    </p>
  ),
  ul: ({ children }) => (
    <ul style={{ margin: '0 0 18px', paddingLeft: 22, display: 'flex', flexDirection: 'column', gap: 8 }}>
      {children}
    </ul>
  ),
  ol: ({ children }) => (
    <ol style={{ margin: '0 0 18px', paddingLeft: 22, display: 'flex', flexDirection: 'column', gap: 8 }}>
      {children}
    </ol>
  ),
  li: ({ children }) => (
    <li style={{ fontSize: 15.5, lineHeight: 1.7, color: 'var(--text)' }}>{children}</li>
  ),
  a: ({ children, href }) => (
    <a href={href} style={{ color: 'var(--bc)', textDecoration: 'underline' }}>
      {children}
    </a>
  ),
  strong: ({ children }) => <strong style={{ fontWeight: 600 }}>{children}</strong>,
  em: ({ children }) => <em style={{ fontStyle: 'italic' }}>{children}</em>,
  blockquote: ({ children }) => (
    <blockquote
      style={{
        borderLeft: '3px solid var(--bdr2)',
        paddingLeft: 16,
        margin: '0 0 18px',
        color: 'var(--muted)',
        fontStyle: 'italic',
      }}
    >
      {children}
    </blockquote>
  ),
  hr: () => <hr style={{ border: 'none', borderTop: '1px solid var(--bdr)', margin: '28px 0' }} />,
  code: ({ children }) => (
    <code
      style={{
        background: 'var(--bg)',
        border: '1px solid var(--bdr)',
        borderRadius: 5,
        padding: '1px 6px',
        fontSize: 13.5,
        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
      }}
    >
      {children}
    </code>
  ),
};

const REFERENCE_COMPONENTS: Components = {
  h2: ({ children }) => (
    <h2
      id={slugify(nodeToText(children))}
      style={{ fontSize: 13, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '.06em', color: 'var(--muted)', margin: '0 0 12px', scrollMarginTop: 80 }}
    >
      {children}
    </h2>
  ),
  ul: ({ children }) => (
    <ul style={{ margin: 0, paddingLeft: 18, display: 'flex', flexDirection: 'column', gap: 7 }}>
      {children}
    </ul>
  ),
  li: ({ children }) => (
    <li style={{ fontSize: 12.5, lineHeight: 1.6, color: 'var(--muted)' }}>{children}</li>
  ),
  p: ({ children }) => (
    <p style={{ fontSize: 12.5, lineHeight: 1.6, color: 'var(--muted)', margin: '0 0 10px' }}>
      {children}
    </p>
  ),
  a: ({ children, href }) => (
    <a href={href} style={{ color: 'var(--bc)', textDecoration: 'underline' }}>
      {children}
    </a>
  ),
  em: ({ children }) => <em style={{ fontStyle: 'italic' }}>{children}</em>,
};
